rules:
- path: ".werft/build.yaml"
  matchesAll:
  - or: ["repo.ref ~= refs/heads/"]
  - or: ["trigger !== deleted"]
- path: ".werft/deleted.yaml"
  matchesAll:
  - or: ["repo.ref ~= refs/heads/"]
  - or: ["trigger == deleted"]
